name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: get_version
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: battila7/get-version-action@v2
      - name: Set up QEMU
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: ${{ github.ref != 'refs/heads/main' }}
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Publish
        if: ${{ github.ref != 'refs/heads/main' }}
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: make publish-docker-image
