name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: make install

      - name: Build
        if: ${{ github.ref != 'refs/heads/main' }}
        run: make build
      - name: Get Version from Git Tag
        if: ${{ github.ref != 'refs/heads/main' }}
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Set up QEMU
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: ${{ github.ref != 'refs/heads/main' }}
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and Push Docker Images
        if: ${{ github.ref != 'refs/heads/main' }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm/v7,linux/amd64
          push: true
          # :latest can be dangerous when republishing old version... But it's okay for now.
          tags: |
            ghcr.io/${{ github.repository }}/filer:latest
            ghcr.io/${{ github.repository }}/filer:${{ steps.get_version.outputs.version }}

